/*
 * Copyright 2018 Mahdi Khanalizadeh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef HEADER_LIBLINUX_GENERIC_KEYBOARD_H_INCLUDED
#define HEADER_LIBLINUX_GENERIC_KEYBOARD_H_INCLUDED

enum
{
	linux_KG_SHIFT     = 0,
	linux_KG_CTRL      = 2,
	linux_KG_ALT       = 3,
	linux_KG_ALTGR     = 1,
	linux_KG_SHIFTL    = 4,
	linux_KG_KANASHIFT = 4,
	linux_KG_SHIFTR    = 5,
	linux_KG_CTRLL     = 6,
	linux_KG_CTRLR     = 7,
	linux_KG_CAPSSHIFT = 8,

	linux_NR_SHIFT     = 9,
};

enum
{
	linux_NR_KEYS                = 256,
	linux_MAX_NR_KEYMAPS         = 256,
	linux_MAX_NR_OF_USER_KEYMAPS = 256,

	linux_MAX_NR_FUNC            = 256,
};

enum
{
	linux_KT_LATIN  =  0,
	linux_KT_LETTER = 11,
	linux_KT_FN     =  1,
	linux_KT_SPEC   =  2,
	linux_KT_PAD    =  3,
	linux_KT_DEAD   =  4,
	linux_KT_CONS   =  5,
	linux_KT_CUR    =  6,
	linux_KT_SHIFT  =  7,
	linux_KT_META   =  8,
	linux_KT_ASCII  =  9,
	linux_KT_LOCK   = 10,
	linux_KT_SLOCK  = 12,
	linux_KT_DEAD2  = 13,
	linux_KT_BRL    = 14,
};

#define linux_K(t, v) (((t) << 8) | (v))
static inline int linux_KTYP(int const x)
{
	return x >> 8;
}
static inline int linux_KVAL(int const x)
{
	return x & 0xff;
}

enum
{
	linux_K_F1     = linux_K(linux_KT_FN, 0),
	linux_K_F2     = linux_K(linux_KT_FN, 1),
	linux_K_F3     = linux_K(linux_KT_FN, 2),
	linux_K_F4     = linux_K(linux_KT_FN, 3),
	linux_K_F5     = linux_K(linux_KT_FN, 4),
	linux_K_F6     = linux_K(linux_KT_FN, 5),
	linux_K_F7     = linux_K(linux_KT_FN, 6),
	linux_K_F8     = linux_K(linux_KT_FN, 7),
	linux_K_F9     = linux_K(linux_KT_FN, 8),
	linux_K_F10    = linux_K(linux_KT_FN, 9),
	linux_K_F11    = linux_K(linux_KT_FN, 10),
	linux_K_F12    = linux_K(linux_KT_FN, 11),
	linux_K_F13    = linux_K(linux_KT_FN, 12),
	linux_K_F14    = linux_K(linux_KT_FN, 13),
	linux_K_F15    = linux_K(linux_KT_FN, 14),
	linux_K_F16    = linux_K(linux_KT_FN, 15),
	linux_K_F17    = linux_K(linux_KT_FN, 16),
	linux_K_F18    = linux_K(linux_KT_FN, 17),
	linux_K_F19    = linux_K(linux_KT_FN, 18),
	linux_K_F20    = linux_K(linux_KT_FN, 19),
	linux_K_FIND   = linux_K(linux_KT_FN, 20),
	linux_K_INSERT = linux_K(linux_KT_FN, 21),
	linux_K_REMOVE = linux_K(linux_KT_FN, 22),
	linux_K_SELECT = linux_K(linux_KT_FN, 23),
	linux_K_PGUP   = linux_K(linux_KT_FN, 24),
	linux_K_PGDN   = linux_K(linux_KT_FN, 25),
	linux_K_MACRO  = linux_K(linux_KT_FN, 26),
	linux_K_HELP   = linux_K(linux_KT_FN, 27),
	linux_K_DO     = linux_K(linux_KT_FN, 28),
	linux_K_PAUSE  = linux_K(linux_KT_FN, 29),
	linux_K_F21    = linux_K(linux_KT_FN, 30),
	linux_K_F22    = linux_K(linux_KT_FN, 31),
	linux_K_F23    = linux_K(linux_KT_FN, 32),
	linux_K_F24    = linux_K(linux_KT_FN, 33),
	linux_K_F25    = linux_K(linux_KT_FN, 34),
	linux_K_F26    = linux_K(linux_KT_FN, 35),
	linux_K_F27    = linux_K(linux_KT_FN, 36),
	linux_K_F28    = linux_K(linux_KT_FN, 37),
	linux_K_F29    = linux_K(linux_KT_FN, 38),
	linux_K_F30    = linux_K(linux_KT_FN, 39),
	linux_K_F31    = linux_K(linux_KT_FN, 40),
	linux_K_F32    = linux_K(linux_KT_FN, 41),
	linux_K_F33    = linux_K(linux_KT_FN, 42),
	linux_K_F34    = linux_K(linux_KT_FN, 43),
	linux_K_F35    = linux_K(linux_KT_FN, 44),
	linux_K_F36    = linux_K(linux_KT_FN, 45),
	linux_K_F37    = linux_K(linux_KT_FN, 46),
	linux_K_F38    = linux_K(linux_KT_FN, 47),
	linux_K_F39    = linux_K(linux_KT_FN, 48),
	linux_K_F40    = linux_K(linux_KT_FN, 49),
	linux_K_F41    = linux_K(linux_KT_FN, 50),
	linux_K_F42    = linux_K(linux_KT_FN, 51),
	linux_K_F43    = linux_K(linux_KT_FN, 52),
	linux_K_F44    = linux_K(linux_KT_FN, 53),
	linux_K_F45    = linux_K(linux_KT_FN, 54),
	linux_K_F46    = linux_K(linux_KT_FN, 55),
	linux_K_F47    = linux_K(linux_KT_FN, 56),
	linux_K_F48    = linux_K(linux_KT_FN, 57),
	linux_K_F49    = linux_K(linux_KT_FN, 58),
	linux_K_F50    = linux_K(linux_KT_FN, 59),
	linux_K_F51    = linux_K(linux_KT_FN, 60),
	linux_K_F52    = linux_K(linux_KT_FN, 61),
	linux_K_F53    = linux_K(linux_KT_FN, 62),
	linux_K_F54    = linux_K(linux_KT_FN, 63),
	linux_K_F55    = linux_K(linux_KT_FN, 64),
	linux_K_F56    = linux_K(linux_KT_FN, 65),
	linux_K_F57    = linux_K(linux_KT_FN, 66),
	linux_K_F58    = linux_K(linux_KT_FN, 67),
	linux_K_F59    = linux_K(linux_KT_FN, 68),
	linux_K_F60    = linux_K(linux_KT_FN, 69),
	linux_K_F61    = linux_K(linux_KT_FN, 70),
	linux_K_F62    = linux_K(linux_KT_FN, 71),
	linux_K_F63    = linux_K(linux_KT_FN, 72),
	linux_K_F64    = linux_K(linux_KT_FN, 73),
	linux_K_F65    = linux_K(linux_KT_FN, 74),
	linux_K_F66    = linux_K(linux_KT_FN, 75),
	linux_K_F67    = linux_K(linux_KT_FN, 76),
	linux_K_F68    = linux_K(linux_KT_FN, 77),
	linux_K_F69    = linux_K(linux_KT_FN, 78),
	linux_K_F70    = linux_K(linux_KT_FN, 79),
	linux_K_F71    = linux_K(linux_KT_FN, 80),
	linux_K_F72    = linux_K(linux_KT_FN, 81),
	linux_K_F73    = linux_K(linux_KT_FN, 82),
	linux_K_F74    = linux_K(linux_KT_FN, 83),
	linux_K_F75    = linux_K(linux_KT_FN, 84),
	linux_K_F76    = linux_K(linux_KT_FN, 85),
	linux_K_F77    = linux_K(linux_KT_FN, 86),
	linux_K_F78    = linux_K(linux_KT_FN, 87),
	linux_K_F79    = linux_K(linux_KT_FN, 88),
	linux_K_F80    = linux_K(linux_KT_FN, 89),
	linux_K_F81    = linux_K(linux_KT_FN, 90),
	linux_K_F82    = linux_K(linux_KT_FN, 91),
	linux_K_F83    = linux_K(linux_KT_FN, 92),
	linux_K_F84    = linux_K(linux_KT_FN, 93),
	linux_K_F85    = linux_K(linux_KT_FN, 94),
	linux_K_F86    = linux_K(linux_KT_FN, 95),
	linux_K_F87    = linux_K(linux_KT_FN, 96),
	linux_K_F88    = linux_K(linux_KT_FN, 97),
	linux_K_F89    = linux_K(linux_KT_FN, 98),
	linux_K_F90    = linux_K(linux_KT_FN, 99),
	linux_K_F91    = linux_K(linux_KT_FN, 100),
	linux_K_F92    = linux_K(linux_KT_FN, 101),
	linux_K_F93    = linux_K(linux_KT_FN, 102),
	linux_K_F94    = linux_K(linux_KT_FN, 103),
	linux_K_F95    = linux_K(linux_KT_FN, 104),
	linux_K_F96    = linux_K(linux_KT_FN, 105),
	linux_K_F97    = linux_K(linux_KT_FN, 106),
	linux_K_F98    = linux_K(linux_KT_FN, 107),
	linux_K_F99    = linux_K(linux_KT_FN, 108),
	linux_K_F100   = linux_K(linux_KT_FN, 109),
	linux_K_F101   = linux_K(linux_KT_FN, 110),
	linux_K_F102   = linux_K(linux_KT_FN, 111),
	linux_K_F103   = linux_K(linux_KT_FN, 112),
	linux_K_F104   = linux_K(linux_KT_FN, 113),
	linux_K_F105   = linux_K(linux_KT_FN, 114),
	linux_K_F106   = linux_K(linux_KT_FN, 115),
	linux_K_F107   = linux_K(linux_KT_FN, 116),
	linux_K_F108   = linux_K(linux_KT_FN, 117),
	linux_K_F109   = linux_K(linux_KT_FN, 118),
	linux_K_F110   = linux_K(linux_KT_FN, 119),
	linux_K_F111   = linux_K(linux_KT_FN, 120),
	linux_K_F112   = linux_K(linux_KT_FN, 121),
	linux_K_F113   = linux_K(linux_KT_FN, 122),
	linux_K_F114   = linux_K(linux_KT_FN, 123),
	linux_K_F115   = linux_K(linux_KT_FN, 124),
	linux_K_F116   = linux_K(linux_KT_FN, 125),
	linux_K_F117   = linux_K(linux_KT_FN, 126),
	linux_K_F118   = linux_K(linux_KT_FN, 127),
	linux_K_F119   = linux_K(linux_KT_FN, 128),
	linux_K_F120   = linux_K(linux_KT_FN, 129),
	linux_K_F121   = linux_K(linux_KT_FN, 130),
	linux_K_F122   = linux_K(linux_KT_FN, 131),
	linux_K_F123   = linux_K(linux_KT_FN, 132),
	linux_K_F124   = linux_K(linux_KT_FN, 133),
	linux_K_F125   = linux_K(linux_KT_FN, 134),
	linux_K_F126   = linux_K(linux_KT_FN, 135),
	linux_K_F127   = linux_K(linux_KT_FN, 136),
	linux_K_F128   = linux_K(linux_KT_FN, 137),
	linux_K_F129   = linux_K(linux_KT_FN, 138),
	linux_K_F130   = linux_K(linux_KT_FN, 139),
	linux_K_F131   = linux_K(linux_KT_FN, 140),
	linux_K_F132   = linux_K(linux_KT_FN, 141),
	linux_K_F133   = linux_K(linux_KT_FN, 142),
	linux_K_F134   = linux_K(linux_KT_FN, 143),
	linux_K_F135   = linux_K(linux_KT_FN, 144),
	linux_K_F136   = linux_K(linux_KT_FN, 145),
	linux_K_F137   = linux_K(linux_KT_FN, 146),
	linux_K_F138   = linux_K(linux_KT_FN, 147),
	linux_K_F139   = linux_K(linux_KT_FN, 148),
	linux_K_F140   = linux_K(linux_KT_FN, 149),
	linux_K_F141   = linux_K(linux_KT_FN, 150),
	linux_K_F142   = linux_K(linux_KT_FN, 151),
	linux_K_F143   = linux_K(linux_KT_FN, 152),
	linux_K_F144   = linux_K(linux_KT_FN, 153),
	linux_K_F145   = linux_K(linux_KT_FN, 154),
	linux_K_F146   = linux_K(linux_KT_FN, 155),
	linux_K_F147   = linux_K(linux_KT_FN, 156),
	linux_K_F148   = linux_K(linux_KT_FN, 157),
	linux_K_F149   = linux_K(linux_KT_FN, 158),
	linux_K_F150   = linux_K(linux_KT_FN, 159),
	linux_K_F151   = linux_K(linux_KT_FN, 160),
	linux_K_F152   = linux_K(linux_KT_FN, 161),
	linux_K_F153   = linux_K(linux_KT_FN, 162),
	linux_K_F154   = linux_K(linux_KT_FN, 163),
	linux_K_F155   = linux_K(linux_KT_FN, 164),
	linux_K_F156   = linux_K(linux_KT_FN, 165),
	linux_K_F157   = linux_K(linux_KT_FN, 166),
	linux_K_F158   = linux_K(linux_KT_FN, 167),
	linux_K_F159   = linux_K(linux_KT_FN, 168),
	linux_K_F160   = linux_K(linux_KT_FN, 169),
	linux_K_F161   = linux_K(linux_KT_FN, 170),
	linux_K_F162   = linux_K(linux_KT_FN, 171),
	linux_K_F163   = linux_K(linux_KT_FN, 172),
	linux_K_F164   = linux_K(linux_KT_FN, 173),
	linux_K_F165   = linux_K(linux_KT_FN, 174),
	linux_K_F166   = linux_K(linux_KT_FN, 175),
	linux_K_F167   = linux_K(linux_KT_FN, 176),
	linux_K_F168   = linux_K(linux_KT_FN, 177),
	linux_K_F169   = linux_K(linux_KT_FN, 178),
	linux_K_F170   = linux_K(linux_KT_FN, 179),
	linux_K_F171   = linux_K(linux_KT_FN, 180),
	linux_K_F172   = linux_K(linux_KT_FN, 181),
	linux_K_F173   = linux_K(linux_KT_FN, 182),
	linux_K_F174   = linux_K(linux_KT_FN, 183),
	linux_K_F175   = linux_K(linux_KT_FN, 184),
	linux_K_F176   = linux_K(linux_KT_FN, 185),
	linux_K_F177   = linux_K(linux_KT_FN, 186),
	linux_K_F178   = linux_K(linux_KT_FN, 187),
	linux_K_F179   = linux_K(linux_KT_FN, 188),
	linux_K_F180   = linux_K(linux_KT_FN, 189),
	linux_K_F181   = linux_K(linux_KT_FN, 190),
	linux_K_F182   = linux_K(linux_KT_FN, 191),
	linux_K_F183   = linux_K(linux_KT_FN, 192),
	linux_K_F184   = linux_K(linux_KT_FN, 193),
	linux_K_F185   = linux_K(linux_KT_FN, 194),
	linux_K_F186   = linux_K(linux_KT_FN, 195),
	linux_K_F187   = linux_K(linux_KT_FN, 196),
	linux_K_F188   = linux_K(linux_KT_FN, 197),
	linux_K_F189   = linux_K(linux_KT_FN, 198),
	linux_K_F190   = linux_K(linux_KT_FN, 199),
	linux_K_F191   = linux_K(linux_KT_FN, 200),
	linux_K_F192   = linux_K(linux_KT_FN, 201),
	linux_K_F193   = linux_K(linux_KT_FN, 202),
	linux_K_F194   = linux_K(linux_KT_FN, 203),
	linux_K_F195   = linux_K(linux_KT_FN, 204),
	linux_K_F196   = linux_K(linux_KT_FN, 205),
	linux_K_F197   = linux_K(linux_KT_FN, 206),
	linux_K_F198   = linux_K(linux_KT_FN, 207),
	linux_K_F199   = linux_K(linux_KT_FN, 208),
	linux_K_F200   = linux_K(linux_KT_FN, 209),
	linux_K_F201   = linux_K(linux_KT_FN, 210),
	linux_K_F202   = linux_K(linux_KT_FN, 211),
	linux_K_F203   = linux_K(linux_KT_FN, 212),
	linux_K_F204   = linux_K(linux_KT_FN, 213),
	linux_K_F205   = linux_K(linux_KT_FN, 214),
	linux_K_F206   = linux_K(linux_KT_FN, 215),
	linux_K_F207   = linux_K(linux_KT_FN, 216),
	linux_K_F208   = linux_K(linux_KT_FN, 217),
	linux_K_F209   = linux_K(linux_KT_FN, 218),
	linux_K_F210   = linux_K(linux_KT_FN, 219),
	linux_K_F211   = linux_K(linux_KT_FN, 220),
	linux_K_F212   = linux_K(linux_KT_FN, 221),
	linux_K_F213   = linux_K(linux_KT_FN, 222),
	linux_K_F214   = linux_K(linux_KT_FN, 223),
	linux_K_F215   = linux_K(linux_KT_FN, 224),
	linux_K_F216   = linux_K(linux_KT_FN, 225),
	linux_K_F217   = linux_K(linux_KT_FN, 226),
	linux_K_F218   = linux_K(linux_KT_FN, 227),
	linux_K_F219   = linux_K(linux_KT_FN, 228),
	linux_K_F220   = linux_K(linux_KT_FN, 229),
	linux_K_F221   = linux_K(linux_KT_FN, 230),
	linux_K_F222   = linux_K(linux_KT_FN, 231),
	linux_K_F223   = linux_K(linux_KT_FN, 232),
	linux_K_F224   = linux_K(linux_KT_FN, 233),
	linux_K_F225   = linux_K(linux_KT_FN, 234),
	linux_K_F226   = linux_K(linux_KT_FN, 235),
	linux_K_F227   = linux_K(linux_KT_FN, 236),
	linux_K_F228   = linux_K(linux_KT_FN, 237),
	linux_K_F229   = linux_K(linux_KT_FN, 238),
	linux_K_F230   = linux_K(linux_KT_FN, 239),
	linux_K_F231   = linux_K(linux_KT_FN, 240),
	linux_K_F232   = linux_K(linux_KT_FN, 241),
	linux_K_F233   = linux_K(linux_KT_FN, 242),
	linux_K_F234   = linux_K(linux_KT_FN, 243),
	linux_K_F235   = linux_K(linux_KT_FN, 244),
	linux_K_F236   = linux_K(linux_KT_FN, 245),
	linux_K_F237   = linux_K(linux_KT_FN, 246),
	linux_K_F238   = linux_K(linux_KT_FN, 247),
	linux_K_F239   = linux_K(linux_KT_FN, 248),
	linux_K_F240   = linux_K(linux_KT_FN, 249),
	linux_K_F241   = linux_K(linux_KT_FN, 250),
	linux_K_F242   = linux_K(linux_KT_FN, 251),
	linux_K_F243   = linux_K(linux_KT_FN, 252),
	linux_K_F244   = linux_K(linux_KT_FN, 253),
	linux_K_F245   = linux_K(linux_KT_FN, 254),
	linux_K_UNDO   = linux_K(linux_KT_FN, 255),
};

enum
{
	linux_K_HOLE         = linux_K(linux_KT_SPEC, 0),
	linux_K_ENTER        = linux_K(linux_KT_SPEC, 1),
	linux_K_SH_REGS      = linux_K(linux_KT_SPEC, 2),
	linux_K_SH_MEM       = linux_K(linux_KT_SPEC, 3),
	linux_K_SH_STAT      = linux_K(linux_KT_SPEC, 4),
	linux_K_BREAK        = linux_K(linux_KT_SPEC, 5),
	linux_K_CONS         = linux_K(linux_KT_SPEC, 6),
	linux_K_CAPS         = linux_K(linux_KT_SPEC, 7),
	linux_K_NUM          = linux_K(linux_KT_SPEC, 8),
	linux_K_HOLD         = linux_K(linux_KT_SPEC, 9),
	linux_K_SCROLLFORW   = linux_K(linux_KT_SPEC, 10),
	linux_K_SCROLLBACK   = linux_K(linux_KT_SPEC, 11),
	linux_K_BOOT         = linux_K(linux_KT_SPEC, 12),
	linux_K_CAPSON       = linux_K(linux_KT_SPEC, 13),
	linux_K_COMPOSE      = linux_K(linux_KT_SPEC, 14),
	linux_K_SAK          = linux_K(linux_KT_SPEC, 15),
	linux_K_DECRCONSOLE  = linux_K(linux_KT_SPEC, 16),
	linux_K_INCRCONSOLE  = linux_K(linux_KT_SPEC, 17),
	linux_K_SPAWNCONSOLE = linux_K(linux_KT_SPEC, 18),
	linux_K_BARENUMLOCK  = linux_K(linux_KT_SPEC, 19),

	linux_K_ALLOCATED    = linux_K(linux_KT_SPEC, 126),
	linux_K_NOSUCHMAP    = linux_K(linux_KT_SPEC, 127),
};

enum
{
	linux_K_P0         = linux_K(linux_KT_PAD, 0),
	linux_K_P1         = linux_K(linux_KT_PAD, 1),
	linux_K_P2         = linux_K(linux_KT_PAD, 2),
	linux_K_P3         = linux_K(linux_KT_PAD, 3),
	linux_K_P4         = linux_K(linux_KT_PAD, 4),
	linux_K_P5         = linux_K(linux_KT_PAD, 5),
	linux_K_P6         = linux_K(linux_KT_PAD, 6),
	linux_K_P7         = linux_K(linux_KT_PAD, 7),
	linux_K_P8         = linux_K(linux_KT_PAD, 8),
	linux_K_P9         = linux_K(linux_KT_PAD, 9),
	linux_K_PPLUS      = linux_K(linux_KT_PAD, 10),
	linux_K_PMINUS     = linux_K(linux_KT_PAD, 11),
	linux_K_PSTAR      = linux_K(linux_KT_PAD, 12),
	linux_K_PSLASH     = linux_K(linux_KT_PAD, 13),
	linux_K_PENTER     = linux_K(linux_KT_PAD, 14),
	linux_K_PCOMMA     = linux_K(linux_KT_PAD, 15),
	linux_K_PDOT       = linux_K(linux_KT_PAD, 16),
	linux_K_PPLUSMINUS = linux_K(linux_KT_PAD, 17),
	linux_K_PPARENL    = linux_K(linux_KT_PAD, 18),
	linux_K_PPARENR    = linux_K(linux_KT_PAD, 19),

	linux_NR_PAD       = 20,
};

enum
{
	linux_K_DGRAVE = linux_K(linux_KT_DEAD, 0),
	linux_K_DACUTE = linux_K(linux_KT_DEAD, 1),
	linux_K_DCIRCM = linux_K(linux_KT_DEAD, 2),
	linux_K_DTILDE = linux_K(linux_KT_DEAD, 3),
	linux_K_DDIERE = linux_K(linux_KT_DEAD, 4),
	linux_K_DCEDIL = linux_K(linux_KT_DEAD, 5),

	linux_NR_DEAD  = 6,
};

enum
{
	linux_K_DOWN  = linux_K(linux_KT_CUR, 0),
	linux_K_LEFT  = linux_K(linux_KT_CUR, 1),
	linux_K_RIGHT = linux_K(linux_KT_CUR, 2),
	linux_K_UP    = linux_K(linux_KT_CUR, 3),
};

enum
{
	linux_K_SHIFT     = linux_K(linux_KT_SHIFT, linux_KG_SHIFT),
	linux_K_CTRL      = linux_K(linux_KT_SHIFT, linux_KG_CTRL),
	linux_K_ALT       = linux_K(linux_KT_SHIFT, linux_KG_ALT),
	linux_K_ALTGR     = linux_K(linux_KT_SHIFT, linux_KG_ALTGR),
	linux_K_SHIFTL    = linux_K(linux_KT_SHIFT, linux_KG_SHIFTL),
	linux_K_SHIFTR    = linux_K(linux_KT_SHIFT, linux_KG_SHIFTR),
	linux_K_CTRLL     = linux_K(linux_KT_SHIFT, linux_KG_CTRLL),
	linux_K_CTRLR     = linux_K(linux_KT_SHIFT, linux_KG_CTRLR),
	linux_K_CAPSSHIFT = linux_K(linux_KT_SHIFT, linux_KG_CAPSSHIFT),
};

enum
{
	linux_K_ASC0   = linux_K(linux_KT_ASCII, 0),
	linux_K_ASC1   = linux_K(linux_KT_ASCII, 1),
	linux_K_ASC2   = linux_K(linux_KT_ASCII, 2),
	linux_K_ASC3   = linux_K(linux_KT_ASCII, 3),
	linux_K_ASC4   = linux_K(linux_KT_ASCII, 4),
	linux_K_ASC5   = linux_K(linux_KT_ASCII, 5),
	linux_K_ASC6   = linux_K(linux_KT_ASCII, 6),
	linux_K_ASC7   = linux_K(linux_KT_ASCII, 7),
	linux_K_ASC8   = linux_K(linux_KT_ASCII, 8),
	linux_K_ASC9   = linux_K(linux_KT_ASCII, 9),
	linux_K_HEX0   = linux_K(linux_KT_ASCII, 10),
	linux_K_HEX1   = linux_K(linux_KT_ASCII, 11),
	linux_K_HEX2   = linux_K(linux_KT_ASCII, 12),
	linux_K_HEX3   = linux_K(linux_KT_ASCII, 13),
	linux_K_HEX4   = linux_K(linux_KT_ASCII, 14),
	linux_K_HEX5   = linux_K(linux_KT_ASCII, 15),
	linux_K_HEX6   = linux_K(linux_KT_ASCII, 16),
	linux_K_HEX7   = linux_K(linux_KT_ASCII, 17),
	linux_K_HEX8   = linux_K(linux_KT_ASCII, 18),
	linux_K_HEX9   = linux_K(linux_KT_ASCII, 19),
	linux_K_HEXa   = linux_K(linux_KT_ASCII, 20),
	linux_K_HEXb   = linux_K(linux_KT_ASCII, 21),
	linux_K_HEXc   = linux_K(linux_KT_ASCII, 22),
	linux_K_HEXd   = linux_K(linux_KT_ASCII, 23),
	linux_K_HEXe   = linux_K(linux_KT_ASCII, 24),
	linux_K_HEXf   = linux_K(linux_KT_ASCII, 25),

	linux_NR_ASCII = 26,
};

enum
{
	linux_K_SHIFTLOCK     = linux_K(linux_KT_LOCK, linux_KG_SHIFT),
	linux_K_CTRLLOCK      = linux_K(linux_KT_LOCK, linux_KG_CTRL),
	linux_K_ALTLOCK       = linux_K(linux_KT_LOCK, linux_KG_ALT),
	linux_K_ALTGRLOCK     = linux_K(linux_KT_LOCK, linux_KG_ALTGR),
	linux_K_SHIFTLLOCK    = linux_K(linux_KT_LOCK, linux_KG_SHIFTL),
	linux_K_SHIFTRLOCK    = linux_K(linux_KT_LOCK, linux_KG_SHIFTR),
	linux_K_CTRLLLOCK     = linux_K(linux_KT_LOCK, linux_KG_CTRLL),
	linux_K_CTRLRLOCK     = linux_K(linux_KT_LOCK, linux_KG_CTRLR),
	linux_K_CAPSSHIFTLOCK = linux_K(linux_KT_LOCK, linux_KG_CAPSSHIFT),
};

enum
{
	linux_K_SHIFT_SLOCK     = linux_K(linux_KT_SLOCK, linux_KG_SHIFT),
	linux_K_CTRL_SLOCK      = linux_K(linux_KT_SLOCK, linux_KG_CTRL),
	linux_K_ALT_SLOCK       = linux_K(linux_KT_SLOCK, linux_KG_ALT),
	linux_K_ALTGR_SLOCK     = linux_K(linux_KT_SLOCK, linux_KG_ALTGR),
	linux_K_SHIFTL_SLOCK    = linux_K(linux_KT_SLOCK, linux_KG_SHIFTL),
	linux_K_SHIFTR_SLOCK    = linux_K(linux_KT_SLOCK, linux_KG_SHIFTR),
	linux_K_CTRLL_SLOCK     = linux_K(linux_KT_SLOCK, linux_KG_CTRLL),
	linux_K_CTRLR_SLOCK     = linux_K(linux_KT_SLOCK, linux_KG_CTRLR),
	linux_K_CAPSSHIFT_SLOCK = linux_K(linux_KT_SLOCK, linux_KG_CAPSSHIFT),

	linux_NR_LOCK           = 9,
};

enum
{
	linux_K_BRL_BLANK = linux_K(linux_KT_BRL, 0),
	linux_K_BRL_DOT1  = linux_K(linux_KT_BRL, 1),
	linux_K_BRL_DOT2  = linux_K(linux_KT_BRL, 2),
	linux_K_BRL_DOT3  = linux_K(linux_KT_BRL, 3),
	linux_K_BRL_DOT4  = linux_K(linux_KT_BRL, 4),
	linux_K_BRL_DOT5  = linux_K(linux_KT_BRL, 5),
	linux_K_BRL_DOT6  = linux_K(linux_KT_BRL, 6),
	linux_K_BRL_DOT7  = linux_K(linux_KT_BRL, 7),
	linux_K_BRL_DOT8  = linux_K(linux_KT_BRL, 8),
	linux_K_BRL_DOT9  = linux_K(linux_KT_BRL, 9),
	linux_K_BRL_DOT10 = linux_K(linux_KT_BRL, 10),

	linux_NR_BRL      = 11,
};

enum
{
	linux_MAX_DIACR = 256,
};

#endif // HEADER_LIBLINUX_KEYBOARD_H_INCLUDED
